### PR TITLE
Fix NixOS LiveCD image build

### PR DESCRIPTION
**Pull request by zeorin**
Fixes https://github.com/drduh/YubiKey-Guide/issues/370.

### CODE REVIEW

**Comment by motiejus** [comment]
Can/should this be fixed upstream?

```
# hopenpgp-tools in nixpkgs 23.05 is out-of-date and has a broken build
```

... suggests it should be doable (make broken non-broken, even with backporting)

**Comment by zeorin** [comment]
Upstream was only fixed 2 weeks ago, and NixOS is gearing up for the 23.11 release. I'm actually rather unfamiliar with Haskell packaging in nixpkgs, [though there is some documentation](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/HACKING.md). [I've asked in the #haskell:nixos.org matrix room how to go about this.](https://matrix.to/#/!RbXGJhHMsnQcNIDFWN:nixos.org/$6zcvfDen28-NB1ma-1HIdEOftJYwb82eL91sEHHY6H8?via=nixos.org&via=matrix.org&via=tchncs.de)

**Comment by zeorin** [comment]
The feedback from the packagers is that backports are unfortunately devilishly difficult. However, it's likely that the new version of `hopenpgp-tools` will be packaged in nixpkgs soon. If we're lucky that'll mean it'll be a part of 23.11.

**Comment by zeorin** [comment]
My force-push doesn't include any changes, I just signed the commits (they were unsigned, before).

**Pull request merged**
