### PR TITLE
Adds instructions on changing the PUK

### PR DESCRIPTION
**Pull request by captn3m0**
As discussed in #220

### CODE REVIEW

**Review by Lsh0x — APPROVED** [review]

**Comment by captn3m0** [comment]
Double checking this, please hold off from merging.

**Comment by drduh** [comment]
Let me know when you're ready for review.

**Comment by drduh** [comment]
This look good - okay to merge?

**Comment by crash5** [comment]
PIV and PGP is not two different applet on the device?

**Pull request merged**
