### PR TITLE
Describe how to backup OTP codes

### PR DESCRIPTION
**Pull request by vald-phoenix**

### CODE REVIEW

**Comment by drduh** [comment]
The guide doesn't really explain OTP well and this section could add confusion. Maybe it's worth pointing out OTP is not related to PGP/SSH?

**Comment by vald-phoenix** [comment]
Yes, you're right. Initially, I have had some doubts about where to place it. Maybe, it's even worth to put it to a separate section and name it like "Backup of Yubikey Authenticator"? What do you think?

**Comment by jakommo** [comment]
There is actually an easier way. You can add an OTP to as many keys as you want. Just connect all of them to your machine (or one by one) and select each of them successively in the Yubikey Authenticator and scan the barcode again with each key, then generate the OTP with the last key to proceed and enable OTP. 
There is no time component involved while the setup barcode is shown.  

A bit less secure, but you could also store the barcode (or the secret code that usually exits in addition to the barcode) of each OTP in a safe place and then add OTP to a new key at any later point, using the manual add  in Yubikey Authenticator,

**Comment by dragon788** [comment]
@jakommo except there is a limit of 32 TOTP codes in Yubico Authenticator as far as I'm aware. I end up using Authy for my larger than 32 collection of secrets and try to only sync the most important/frequently used ones to my Yubikey due to this.

**Comment by drduh** [comment]
Let's work on a new, updated PR.

**Pull request closed without merging**
