### PR TITLE
Prefer ECC rather than RSA

### PR DESCRIPTION
**Pull request by btlogy**
In regard to #270, this PR document using ECC rather than RSA.

### CODE REVIEW

**Comment by PhilipMay** [comment]
Interesting PR. @drduh can you please review it?

**Comment by PhilipMay** [comment]
Hmm interesting: https://github.com/drduh/YubiKey-Guide/issues/52#issuecomment-368400890

**Comment by drduh** [comment]
I would rather not change the defaults from RSA to ECC at this time. If you'd like to add these instructions as an alternative addendum, that would be welcome. Thank you!

**Comment by rdlu** [comment]
Just to add some info. (just found this repo).

I had some problems using an ecdsa subkey with gpg4win 4.0.4 + Windows 11 (and a socket to WSL2 VMs) , despite having success for signing and ssh auth on Linux/Mac. It fails on Powershell, even more using a socat socket from the agent to inside WSL2.

So it needs some more careful testing for the ones that still need to use Windows for one reason or another.

(I don't have the logs now, I abandoned the setup in favour of RSA subkeys).

Thanks!

**Comment by iandstanley** [comment]
Dunno about 11 but Win 10’s ssh has some odd compilation options - it doesn’t support PIV and if memory serves me right nor ECCThere is a repo out there that takes the win 10 ssh and turns on the appropriate options but I decided for my use case (PIV) to use a PIV supporting ssh client It may take some digging to resolve On 28 Mar 2023, at 16:17, Rodrigo Dlugokenski ***@***.***> wrote:﻿
Just to add some info. (just found this repo).
I had some problems using an ecdsa subkey with gpg4win 4.0.4 + Windows 11 (and a socket to WSL2 VMs) , despite having success for signing and ssh auth on Linux/Mac. It fails on Powershell, even more using a socat socket from the agent to inside WSL2.
So it needs some more careful testing for the ones that still need to use Windows for one reason or another.
(I don't have the logs now, I abandoned the setup in favour of RSA subkeys).
Thanks!

**Comment by btlogy** [comment]
I may create another PR to propose ECC as an addendum.

**Pull request closed without merging**
