### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MarkStanhope**
updated generate key command to gpg --full-generate-key,

### CODE REVIEW

**Comment by drduh** [comment]
Is this useful? The manual page says this presents more options; which ones are relevant?

**Comment by MarkStanhope** [comment]
on debian (kali) variant you cant select the key length, just name and
email address.  I was working on the assumption that this is a general
change.


Mark

**Comment by webhat** [comment]
With my local versions of gpg (1.4.22 and 2.0.30) I get:
```
gpg: invalid option "--full-generate-key"
```

It looks like `full-generate-key` was fairly recently introduced, 2.1.19, and might require people to upgrade their gpg first, rather than being immediately able to follow along with the instructions.

**Comment by bhundven** [comment]
`--full-generate-key` was added in gnupg-2.1.17, which replaced `--full-gen-key` that was added in 2.1.0-beta-864.

The commit message for `--full-gen-key`:
```
commit f3625bb018fa8d5bc754f982996f8788386f0a9d
Author: Werner Koch <wk@gnupg.org>
Date:   Sat Sep 27 15:14:13 2014 +0200

    gpg: Simplify command --gen-key and add --full-gen-key.
    
    * g10/gpg.c (aFullKeygen): New.
    (opts): Add command --full-key-gen.
    (main): Implement it.
    * g10/keygen.c (DEFAULT_STD_ALGO): Replace wrong GCRY_PK_RSA although
    the value is identical.
    (DEFAULT_STD_CURVE): New.
    (DEFAULT_STD_SUBALGO): New.
    (DEFAULT_STD_SUBKEYSIZE): New.
    (DEFAULT_STD_SUBCURVE): New.
    (quick_generate_keypair): Use new macros here.
    (generate_keypair): Add arg "full" and fix call callers. Do not ask
    for keysize in non-full node.
    (ask_user_id): Add arg "full" and simplify for non-full mode.
```

**Pull request closed without merging**
